export const DEFAULT_FIRST_SLIDE_PROMPT =
  "Create a TikTok slide variation with the same hook, bit different imagery (altering the vibe, objects and elements in the image) and a raw, organic, real vibe. Keep the same background type, layout, margins, text size, and text placement. Change outfits, vibe and people subtly (if people are present in the image). Maintain clarity and readability.";

export const DEFAULT_OTHER_SLIDES_PROMPT =
  "This is a TikTok carousel slide. Generate a new variation that stays very close to the original while feeling refreshed. HARD CONSTRAINTS (DO NOT VIOLATE): If the original image does not contain a human, do not add a human under any circumstance. Do not add faces, people, silhouettes, body parts, reflections, shadows, or any human-like forms. Treat humans as forbidden elements unless explicitly present in the original image. Paraphrase the text without changing the core message. Use new imagery with a different vibe. If and only if a human is present in the original image, keep the same gender, change the face and outfit, and do not add or remove people. If no human is present, keep the imagery strictly object-based, abstract, or environmental. Do not reuse the same background. Keep the same background category (solid color, gradient, room, outdoor, abstract, texture, etc.) but make controlled changes. Change at least 4 of the following: color palette, lighting, texture or material feel, or environmental details. The background should feel clearly different at first glance while still belonging to the same design system. Match the original visual structure exactly, including margins, text alignment, font scale, and visual hierarchy. Do not move or resize text blocks. The result should look like an alternate take, not a redesign. Avoid dramatic changes and think iteration, not reinvention. Prioritize readability first, visual balance second, and consistency with the original slide.";

export const DEFAULT_INPUT_QUALITY: "low" | "high" = "low";
export const DEFAULT_OUTPUT_QUALITY: "low" | "medium" | "high" = "medium";
export const DEFAULT_OUTPUT_FORMAT: "png" | "jpeg" | "webp" = "jpeg";
export const DEFAULT_NUM_SETS = 1;
